=begin
#SurveyMonkey API V3 Minimal

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CollectorsAndInviteMessagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CollectorsAndInviteMessagesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CollectorsAndInviteMessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CollectorsAndInviteMessagesApi' do
    it 'should create an instance of CollectorsAndInviteMessagesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CollectorsAndInviteMessagesApi)
    end
  end

  # unit tests for create_a_survey_collector
  # Create a survey collector
  # Creates a webline or email collector for a given survey
  # @param [Hash] opts the optional parameters
  # @option opts [Model310099766CollectorsBody] :body 
  # @return [nil]
  describe 'create_a_survey_collector test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_a_collector_by_id
  # Get a collector by id
  # Get a collector by id
  # @param collector_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_a_collector_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_survey_collectors
  # Get survey collectors
  # Get a list of collectors for a given survey
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_survey_collectors test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
