=begin
#SurveyMonkey API V3 Minimal

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/collector_id_responses_body'
require 'swagger_client/models/inline_response_201'
require 'swagger_client/models/model_310099766_collectors_body'
require 'swagger_client/models/page_id_questions_body'
require 'swagger_client/models/questions_question_id_body'
require 'swagger_client/models/surveys_310099766_body'
require 'swagger_client/models/v3_contacts_body'
require 'swagger_client/models/v3_surveys_body'
require 'swagger_client/models/v3_webhooks_body'
require 'swagger_client/models/v3collectors_collector_i_dresponses_answers'
require 'swagger_client/models/v3collectors_collector_i_dresponses_pages'
require 'swagger_client/models/v3collectors_collector_i_dresponses_questions'
require 'swagger_client/models/v3contacts_custom_fields'
require 'swagger_client/models/v3surveys310099766pages_page_i_dquestions_answers'
require 'swagger_client/models/v3surveys310099766pages_page_i_dquestions_answers_choices'
require 'swagger_client/models/v3surveys310099766pages_page_i_dquestions_headings'
require 'swagger_client/models/v3surveys310099766pages_page_i_dquestions_random_assignment'
require 'swagger_client/models/webhooks_webhook_id_body'
require 'swagger_client/models/webhooks_webhook_id_body_1'

# APIs
require 'swagger_client/api/collectors_and_invite_messages_api'
require 'swagger_client/api/contacts_and_contact_lists_api'
require 'swagger_client/api/errors_api'
require 'swagger_client/api/survey_responses_api'
require 'swagger_client/api/surveys_pages_and_questions_api'
require 'swagger_client/api/users_and_groups_api'
require 'swagger_client/api/webhooks_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
